// SkillButtonData.js

export const skillButtons = [
  {
    id: 1,
    className: "top-[10%] md:top-[7%] left-[5%] md:left-[10%] bg-[url('/logos/git.png')]",
    animate: { rotate: [0, 10, -10, 0], scale: [1, 1.1, 1] },
    transition: { duration: 4, repeat: Infinity, ease: "easeInOut" },
    percent: 65,
  },
  {
    id: 2,
    className: "top-[14%] md:top-[10%] left-[20%] md:left-[25%] bg-[url('/logos/ChatGPT.png')]",
    animate: { y: [0, -15, 0] },
    transition: { duration: 3.5, delay: 1, repeat: Infinity, ease: "easeInOut" },
    percent: 88,
  },
  {
    id: 3,
    className: "top-[22%] left-[40%] md:left-[50%] bg-[url('/logos/java.png')]",
    animate: { scale: [1, 1.2, 1], rotate: [0, 5, -5, 0] },
    transition: { duration: 5, delay: 2, repeat: Infinity, ease: "easeInOut" },
    percent: 82,
  },
  {
    id: 4,
    className: "top-[28%] left-[6%] md:left-[10%] bg-[url('/logos/figma.png')]",
    animate: { y: [0, 10, -10, 0] },
    transition: { duration: 4, delay: 1.5, repeat: Infinity, ease: "easeInOut" },
    percent: 74,
  },
  {
    id: 5,
    className: "top-[40%] right-[5%] md:right-[10%] bg-[url('/logos/react.png')]",
    animate: { rotate: [0, 360] },
    transition: { duration: 8, delay: 0.5, repeat: Infinity, ease: "linear" },
    percent: 91,
  },
  {
    id: 6,
    className: "top-[44%] left-[5%] bg-[url('/logos/vs-code.png')]",
    animate: { scale: [1, 1.3, 1] },
    transition: { duration: 6, delay: 2.5, repeat: Infinity, ease: "easeInOut" },
    percent: 68,
  },
  {
    id: 7,
    className: "top-[18%] left-[75%] md:left-[80%] bg-[url('/logos/css.png')]",
    animate: { y: [0, -20, 0], rotate: [0, 5, 0] },
    transition: { duration: 4, delay: 3, repeat: Infinity, ease: "easeInOut" },
    percent: 84,
  },
  {
    id: 8,
    className: "top-[60%] right-[10%] md:right-[15%] bg-[url('/logos/html.png')]",
    animate: { x: [0, -10, 10, 0] },
    transition: { duration: 5, delay: 1.2, repeat: Infinity, ease: "easeInOut" },
    percent: 90,
  },
  {
    id: 9,
    className: "bottom-[12%] left-[10%] md:left-[15%] bg-[url('/logos/mysql.png')]",
    animate: { scale: [1, 1.2, 1], y: [0, 10, 0] },
    transition: { duration: 4.5, delay: 0.8, repeat: Infinity, ease: "easeInOut" },
    percent: 77,
  },
  {
    id: 10,
    className: "bottom-[25%] right-[15%] md:right-[25%] bg-[url('/logos/pintrest.png')]",
    animate: { y: [0, -15, 0] },
    transition: { duration: 3, delay: 2, repeat: Infinity, ease: "easeInOut" },
    percent: 45,
  },
  {
    id: 11,
    className: "bottom-[20%] left-[5%] bg-[url('/logos/spb.png')]",
    animate: { rotate: [0, 15, -15, 0] },
    transition: { duration: 6, delay: 1, repeat: Infinity, ease: "easeInOut" },
    percent: 58,
  },
  {
    id: 12,
    className: "bottom-[14%] right-[12%] md:right-[16%] bg-[url('/logos/rive.png')]",
    animate: { scale: [1, 1.4, 1], rotate: [0, 10, -10, 0] },
    transition: { duration: 5, delay: 0.6, repeat: Infinity, ease: "easeInOut" },
    percent: 80,
  },
  {
    id: 13,
    className: "bottom-[10%] left-[50%] md:left-[60%] bg-[url('/logos/bgrmv.png')]",
    animate: { x: [0, 20, -20, 0] },
    transition: { duration: 7, delay: 1.3, repeat: Infinity, ease: "easeInOut" },
    percent: 61,
  },
  {
    id: 14,
    className: "bottom-[20%] right-[50%] md:right-[60%] bg-[url('/logos/mongo.png')]",
    animate: { rotate: [0, 360] },
    transition: { duration: 10, delay: 1, repeat: Infinity, ease: "linear" },
    percent: 73,
  },
];
